name: Release

on:
  repository_dispatch:
    types:
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create release
        uses: actions/create-release@v1
        id: release
        with:
          tag_name: ${{ github.event.client_payload.version }}
          release_name: v${{ github.event.client_payload.version }}
          body: '${{ github.event.client_payload.notes }}'
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Notify SDK repository
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: getstudiobridge/sdk
          event-type: published
          client-payload: |
            {
              "version": "${{ github.event.client_payload.version }}",
              "run_id": "${{ github.event.client_payload.run_id }}",
              "upload_url": "${{ steps.release.outputs.upload_url }}"
            }
