name: Release

on:
  repository_dispatch:
    types:
      - Release

jobs:
  release:
    runs-on: ubuntu-latest
    container: node:lts
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Bump version
        run: "sed -i 's/\\(\"version\": \"\\).*\"/\\1${{ github.event.client_payload.version }}\"/g' package.json"
      - name: Bump react package version
        run: "sed -i 's/\\(\"version\": \"\\).*\"/\\1${{ github.event.client_payload.version }}\"/g' package.json"
      - name: Install dependencies
        run: yarn
      - name: Install react package dependencies
        run: yarn --cwd react
      - name: Link packages
        run: yarn link && yarn --cwd react link foobartestxyz
      - name: Compile
        run: yarn build
      - name: Compile react package
        run: yarn --cwd react build
      - name: Authenticate with NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Publish NPM package
        run: yarn publish --non-interactive
      - name: Create release
        uses: actions/create-release@v1
        id: release
        with:
          tag_name: ${{ github.event.client_payload.version }}
          release_name: ${{ github.event.client_payload.version }}
          body: '${{ github.event.client_payload.notes }}'
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Notify SDK repository
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: getbounce/sdk
          event-type: Publish
          client-payload: |
            {
              "version": ${{ toJson(github.event.client_payload.version) }},
              "run_id": ${{ toJson(github.event.client_payload.run_id) }},
              "upload_url": ${{ toJson(steps.release.outputs.upload_url) }}
            }
