name: Release

on:
  repository_dispatch:
    types:
      - Release

jobs:
  release:
    runs-on: ubuntu-latest
    container: node:lts
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Bump Core version
        run: "sed -i 's/\\(\"version\": \"\\).*\"/\\1${{ github.event.client_payload.version }}\"/g' packages/core/package.json"
      - name: Bump CLI version
        run: "sed -i 's/\\(\"version\": \"\\).*\"/\\1${{ github.event.client_payload.version }}\"/g' packages/cli/package.json"
      # - name: Bump React version
      #   run: "sed -i 's/\\(\"version\": \"\\).*\"/\\1${{ github.event.client_payload.version }}\"/g' packages/react/package.json"

      - name: Install dependencies
        run: yarn
      - name: Compile
        run: yarn workspaces run build

      - name: Authenticate with NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Publish Core package
        run: cd packages/core && yarn publish --non-interactive
      - name: Publish CLI package
        run: cd packages/cli && yarn publish --non-interactive
      # - name: Publish React package
      #   run: cd packages/react && yarn publish --non-interactive

      - name: Create release
        uses: actions/create-release@v1
        id: release
        with:
          tag_name: ${{ github.event.client_payload.version }}
          release_name: ${{ github.event.client_payload.version }}
          body: '${{ github.event.client_payload.notes }}'
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Notify SDK repository
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: getsidechain/sdk
          event-type: Publish
          client-payload: |
            {
              "version": ${{ toJson(github.event.client_payload.version) }},
              "run_id": ${{ toJson(github.event.client_payload.run_id) }},
              "upload_url": ${{ toJson(steps.release.outputs.upload_url) }}
            }
