name: Release

on:
  repository_dispatch:
    types:
      - Release

jobs:
  release:
    runs-on: ubuntu-latest
    container: node:lts
    steps:
      - name: Install JQ
        run: sudo apt update && sudo apt install -y jq
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Bump version
        run: jq '.version = "${{ github.event.client_payload.version }}"' package.json > package.json
      - name: Install dependencies
        run: yarn
      - name: Compile
        run: yarn build
      - name: Bundle
        run: yarn pack
      - name: Upload build tmp
        uses: actions/upload-artifact@v2
        with:
          name: studiobridge-v${{ github.event.client_payload.version }}.tgz
          path: studiobridge-v${{ github.event.client_payload.version }}.tgz
      - name: Create release
        uses: actions/create-release@v1
        id: release
        with:
          tag_name: ${{ github.event.client_payload.version }}
          release_name: ${{ github.event.client_payload.version }}
          body: '${{ github.event.client_payload.notes }}'
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Notify SDK repository
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: getstudiobridge/sdk
          event-type: Publish
          client-payload: |
            {
              "version": ${{ toJson(github.event.client_payload.version) }},
              "run_id": ${{ toJson(github.event.client_payload.run_id) }},
              "upload_url": ${{ toJson(steps.release.outputs.upload_url) }}
            }
